language: minimal
sudo: required
services: docker

install: true
script: ./scripts/docker-build

deploy:
  provider: script
  script: TAG=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} ./scripts/docker-push
  skip_cleanup: true
  on:
    branch: '*'
