version: '2'
services:
  app:
    image: smartsupp/status
    environment:
      STATUS_AGGREGATOR_CONFIG: |
        {
          "upstreamUrls": [
            "http://nginx1",
            "http://nginx2"
          ]
        }

  nginx1:
    image: nginx:alpine

  nginx2:
    image: nginx:alpine
