version: '2'
services:
  app:
    image: smartsupp/status-aggregator
    environment:
      STATUS_AGGREGATOR_CONFIG: |
        {
          "upstreamUrls": [
            "http://nginx1",
            "http://nginx2"
          ]
        }

  nginx1:
    image: nginx:alpine

  nginx2:
    image: nginx:alpine

  curl:
    image: appropriate/curl
    command: 'true'
